name: iOS TestFlight

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  testflight:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2" # 또는 "16.1", "16.0" 등 설치된 버전

      - name: Ruby (bundler cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: CocoaPods install
        run: bundle exec pod install --deployment

      - name: Build match basic auth header
        run: |
          set -euo pipefail
          AUTH_B64="$(printf "x-access-token:%s" "${{ secrets.MATCH_PAT }}" | base64 | tr -d '\r\n')"
          echo "MATCH_GIT_BASIC_AUTHORIZATION=$AUTH_B64" >> "$GITHUB_ENV"

      - name: Build & Upload TestFlight
        env:
          CI: "true"

          # ASC
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}

          # match
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_PAT: ${{ secrets.MATCH_PAT }}

          MATCH_GIT_BASIC_AUTHORIZATION: ${{ env.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}

        run: bundle exec fastlane ios beta
